### ISSUE TITLE
set_local_sources should create folder inside DOT_SAGE not SAGE_SHARE

### ISSUE THREAD

**Issue by kiwifb** [sagemath/p_group_cohomology#3]
I am currently trying to package p_group_cohomology for sage-on-gentoo. The first issue is really that's 4 packages in one box, but that another story and I am expecting the packaging to mature eventually.
I tried to doctest my install and I had this particular failure (probably the root cause of many more that I see)
```
File "/usr/lib/python3.8/site-packages/pGroupCohomology/auxiliaries.py", line 260, in pGroupCohomology.auxiliaries.CohoFormatter.reset
Failed example:
    CohomologyRing.reset()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/sage/doctest/forker.py", line 714, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib/python3.8/site-packages/sage/doctest/forker.py", line 1133, in compile_and_execute
        exec(compiled, globs)
      File "<doctest pGroupCohomology.auxiliaries.CohoFormatter.reset[2]>", line 1, in <module>
        CohomologyRing.reset()
      File "/usr/lib/python3.8/site-packages/pGroupCohomology/factory.py", line 397, in reset
        self.set_local_sources(True)  # use the default location of the local sources
      File "/usr/lib/python3.8/site-packages/pGroupCohomology/factory.py", line 638, in set_local_sources
        os.makedirs(folder)  # may produce an error
      File "/usr/lib/python3.8/os.py", line 223, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: '/usr/share/sage/pGroupCohomology'
```
Of course permission is denied since this is a system location. At first I thought may be there was some stuff in that folder, but it just doesn't exist by default. The more I read about the function the less I understand why you want to write in a system space rather than a personal space. Even in vanilla sage that you are building yourself in your home space it would be inappropriate even if it doesn't cause permission problems.

**Comment by simon-king-jena** [comment]
Hi!

Am 04.02.21 um 22:20 schrieb François Bissey:
>
> I am currently trying to package p_group_cohomology for
> sage-on-gentoo. The first issue is really that's 4 packages in one box,
>
There currently are tickets to beak p_group_cohomology into smaller
pieces. I don't know about the status of them, as I'm currently much
involved in teaching.
> |File
> "/usr/lib/python3.8/site-packages/pGroupCohomology/auxiliaries.py",
> line 260, in pGroupCohomology.auxiliaries.CohoFormatter.reset Failed
> example: CohomologyRing.reset() Exception raised: Traceback (most
> recent call last): File
> "/usr/lib/python3.8/site-packages/sage/doctest/forker.py", line 714,
> in _run self.compile_and_execute(example, compiler, test.globs) File
> "/usr/lib/python3.8/site-packages/sage/doctest/forker.py", line 1133,
> in compile_and_execute exec(compiled, globs) File "<doctest
> pGroupCohomology.auxiliaries.CohoFormatter.reset[2]>", line 1, in
> <module> CohomologyRing.reset() File
> "/usr/lib/python3.8/site-packages/pGroupCohomology/factory.py", line
> 397, in reset self.set_local_sources(True) # use the default location
> of the local sources File
> "/usr/lib/python3.8/site-packages/pGroupCohomology/factory.py", line
> 638, in set_local_sources os.makedirs(folder) # may produce an error
> File "/usr/lib/python3.8/os.py", line 223, in makedirs mkdir(name,
> mode) PermissionError: [Errno 13] Permission denied:
> '/usr/share/sage/pGroupCohomology' |
>
> Of course permission is denied since this is a system location. At
> first I thought may be there was some stuff in that folder, but it
> just doesn't exist by default. The more I read about the function the
> less I understand why you want to write in a system space rather than
> a personal space. Even in vanilla sage that you are building yourself
> in your home space it would be inappropriate even if it doesn't cause
> permission problems.
>
Local data for the package are in two different locations.

  * There is a data base that is shared by all users of a single Sage
    install (referred to as "local sources") and is provided as part of
    the package. It is installed in SAGE_LOCAL/share/pGroupCohomology.
    It can of course be assumed that there is write permission during
    package initialisation, but I certainly do not assume write
    permission to the _default location_ at run time! It is enough that
    the user can read from SAGE_LOCAL/share.
    Write permission is only required if the default location was not
    created during installation or if a user wants to create new local
    sources in a non-default location (but then it is fair to assume she
    has write permission).
  * There is a data base for each individual user (referred to as
    "workspace"). It is located in DOT_SAGE/pGroupCohomology. Of course
    it is assumed that a user has write permission in his/her DOT_SAGE
    folder.

The error you report indicates the folder of the default location of the
local sources was not created during installation and the user has no
write permission at runtime.

Is it perhaps the case that for sage-on-gentoo, SAGE_SHARE has a
different value during package installation than at runtime, and that in
addition SAGE_SHARE is a system folder? The former would be very odd,
but would explain the error.

Best regards,
Simon

**Comment by kiwifb** [comment]
I have checked sage's `spkg-install.in` but it doesn't install a database or create that particular folder. If there was, it would be a 5th package in the way I count them. 

I can see a `db` folder which only has a file called license in it. 

`setup.py` from pGroupCohomology doesn't create or populate `SAGE_LOCAL/share/pGroupCohomology` as far as I can see. Even if it was created, Gentoo's package manager doesn't install empty folder by default (you can get around that by putting a special dot file in it).

Now that I know that it is not supposed to be written at runtime but could contain stuff, I can do something about it.

You should consider creating the folder with `spkg-install.in` rather than relying `set_local_sources` to create it if it is missing as is the case currently. And that is a runtime action.

**Comment by kiwifb** [comment]
After giving some more thoughts, in vanilla sage the folder is probably created when running `spkg-postinst.in` to build the documentation. The documentation building process probably do calls that eventually end up calling `set_local_sources` and create the folder (as you can guess I am not currently building the documentation).

Which is naughty and would have made portage scream at me if I was building the documentation, because the build process would have tried to touch the live file system. For reminders, packagers, and that includes the like of `pip`, do building in a "sandbox", the installation is also done in a sandbox and once any post installation tasks have been performed, the package is finally "merged" into the live file system. 

In packaging terms, as a runtime dependency of the pGroupCohomology (the python bindings), that database stuff has to be installed first.

**Comment by simon-king-jena** [comment]
Hi François,

I'm not sure what "file" you are talking about. Anyway, the local
sources database has nothing to do with building the documentation and
has nothing to do with spkg-postinst.in. The database is supposed to be
installed when the modular_resolution subpackage is iinstalled.

Best regards,
Simon

Am 04.02.21 um 23:32 schrieb François Bissey:

**Comment by kiwifb** [comment]
OK, thanks for that. I found it and there is indeed a mismatch in location that is my fault. 

When you talked about db I was thinking you were referring to https://github.com/sagemath/p_group_cohomology/tree/master/src/db 
Is the license file in there, the license for the db installed by modular_resolution by any chance?

**Comment by kiwifb** [comment]
Not that I fixed the location issue I am getting this
```
File "/usr/lib/python3.8/site-packages/pGroupCohomology/auxiliaries.py", line 206, in pGroupCohomology.auxiliaries.CohoFormatter
Failed example:
    CohomologyRing.reset()
Expected nothing
Got:
    set_local_sources:
        WARNING: '/usr/share/pGroupCohomology' is not writeable
**********************************************************************
File "/usr/lib/python3.8/site-packages/pGroupCohomology/auxiliaries.py", line 260, in pGroupCohomology.auxiliaries.CohoFormatter.reset
Failed example:
    CohomologyRing.reset()
Expected nothing
Got:
    set_local_sources:
        WARNING: '/usr/share/pGroupCohomology' is not writeable
**********************************************************************
File "/usr/lib/python3.8/site-packages/pGroupCohomology/auxiliaries.py", line 275, in pGroupCohomology.auxiliaries.CohoFormatter.reset
Failed example:
    CohomologyRing.reset()    # indirect doctest
Expected nothing
Got:
    set_local_sources:
        WARNING: '/usr/share/pGroupCohomology' is not writeable
**********************************************************************
File "/usr/lib/python3.8/site-packages/pGroupCohomology/auxiliaries.py", line 307, in pGroupCohomology.auxiliaries.CohoFormatter.format
Failed example:
    CohomologyRing.reset()
Expected nothing
Got:
    set_local_sources:
        WARNING: '/usr/share/pGroupCohomology' is not writeable
**********************************************************************
```
Do you really need to check it is writable?
