### ISSUE TITLE
Does not work with Singular >= 4.2.0p3

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/p_group_cohomology#4]
Singular renamed `poly.lib`, which has broken p_group_cohomology in Sage 9.4 

https://github.com/mkoeppe/sage/runs/3428253504?check_suite_focus=true

```
estsuite summary for modular_resolution 1.1
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Running doctests with ID 2021-08-27-19-55-56-20890de7.
Using --optional=debian,dochtml,e_antic,meataxe,normaliz,pari_elldata,pari_galpol,pari_nftables,pari_seadata,pip,plantri,polylib,primecount,pycosat,pynormaliz,pysingular,python_igraph,sage,sage_spkg,texttable
Sorting sources by runtime so that slower doctests are run first....
Doctesting 13 files using 3 threads.
sage -t --long --warn-long 80.0 --random-seed=0 pGroupCohomology-3.3.2/pGroupCohomology/auxiliaries.py
**********************************************************************
File "pGroupCohomology-3.3.2/pGroupCohomology/auxiliaries.py", line 111, in pGroupCohomology.auxiliaries.unpickle_old_mtx.__call__
Failed example:
    print(CohomologyRing(64,12))  # indirect doctest
Exception raised:
    Traceback (most recent call last):
      File "/sage/local/lib/python3.9/site-packages/pGroupCohomology/factory.py", line 1223, in _get_p_group_from_cache_or_db
        OUT = load(os.path.join(root_workspace,file_name)) # realpath here?
      File "sage/misc/persist.pyx", line 187, in sage.misc.persist.load (build/cythonized/sage/misc/persist.c:2925)
        with open(filename, 'rb') as fobj:
      File "sage/misc/persist.pyx", line 188, in sage.misc.persist.load (build/cythonized/sage/misc/persist.c:2875)
        X = loads(fobj.read(), compress=compress, **kwargs)
      File "sage/misc/persist.pyx", line 972, in sage.misc.persist.loads (build/cythonized/sage/misc/persist.c:7587)
        ans = unpickler.load()
      File "pGroupCohomology/cohomology.pyx", line 219, in pGroupCohomology.cohomology.COHO_unpickle
      File "pGroupCohomology/cohomology.pyx", line 3880, in pGroupCohomology.cohomology.COHO.__setstate__
      File "/sage/local/lib/python3.9/site-packages/sage/interfaces/singular.py", line 877, in lib
        self.eval('LIB "%s"'%lib)
      File "/sage/local/lib/python3.9/site-packages/sage/interfaces/singular.py", line 674, in eval
        raise SingularError('Singular error:\n%s'%s)
    sage.interfaces.singular.SingularError: Singular error:
       ? cannot open poly.lib
       ? error occurred in or before STDIN line 13: `LIB "poly.lib";`

```

**Comment by simon-king-jena** [comment]
What is the new name of "poly.lib"? Or rather: Where to get its functionality from?

**Comment by simon-king-jena** [comment]
OK, apparently SINGULAR 4-2-0 "renamed poly.lib to polylib.lib". Why do they do such (from my perspective) useless changes?

**Comment by mkoeppe** [comment]
No idea what motivated this change...
